"""initial directory schema

Baseline matching the models: faculties, departments, service units,
service responsibilities and user affiliations (RESTRICT foreign keys).

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 15:53:11.915403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faculties_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_faculties_id'), ['id'], unique=False)

    op.create_table('service_units',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_units_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_service_units_id'), ['id'], unique=False)

    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('faculty_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_departments_id'), ['id'], unique=False)

    op.create_table('service_responsibilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('service_unit_id', sa.String(length=36), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('faculty_id', sa.String(length=36), nullable=True),
    sa.Column('role_title', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='responsibilitystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_unit_id'], ['service_units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_responsibilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_responsibilities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_responsibilities_user_id'), ['user_id'], unique=False)

    op.create_table('user_affiliations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('faculty_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'department_id', name='uq_user_department_affiliation')
    )
    with op.batch_alter_table('user_affiliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_affiliations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_affiliations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_affiliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_affiliations_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_affiliations_id'))

    op.drop_table('user_affiliations')
    with op.batch_alter_table('service_responsibilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_responsibilities_user_id'))
        batch_op.drop_index(batch_op.f('ix_service_responsibilities_id'))

    op.drop_table('service_responsibilities')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_id'))
        batch_op.drop_index(batch_op.f('ix_departments_code'))

    op.drop_table('departments')
    with op.batch_alter_table('service_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_units_id'))
        batch_op.drop_index(batch_op.f('ix_service_units_code'))

    op.drop_table('service_units')
    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faculties_id'))
        batch_op.drop_index(batch_op.f('ix_faculties_code'))

    op.drop_table('faculties')
    # Named enum types persist after drop_table on PostgreSQL; no-op on SQLite.
    sa.Enum(name='responsibilitystatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
